### ISSUE TITLE
Why i can't run the code with default setting

### ISSUE THREAD

**Issue by loadder** [Clarifai/few-shot-ctm#8]
I just run as the readme writes
`python main.py --yaml_file configs/demo/mini/20way_1shot.yaml`
 and i got this error
`Traceback (most recent call last):
  File "main.py", line 204, in <module>
    main()
  File "main.py", line 28, in main
    opts = Config(config['options']['ctrl.yaml_file'], config['options'])
  File "/home/few-shot-ctm/core/config.py", line 111, in __init__
    merge_cfg_from_file(yaml_file, self)
  File "/home/few-shot-ctm/tools/general_utils.py", line 278, in merge_cfg_from_file
    _merge_a_into_b(yaml_cfg, _config)
  File "/hom/few-shot-ctm/tools/general_utils.py", line 334, in _merge_a_into_b
    _merge_a_into_b(v, b[k], stack=stack_push)
  File "/home/few-shot-ctm/tools/general_utils.py", line 324, in _merge_a_into_b
    raise KeyError('Non-existent config key: {}'.format(full_key))
KeyError: 'Non-existent config key: ctmnet.pred_source'`
python version 3.6.8 pytorch version 1.2.0
Any idea?

**Comment by wsj1996** [comment]
I had  this problem too

**Comment by KaiHoo** [comment]
Same here. Any suggestions? Thanks!

**Comment by nikkiccq** [comment]
I have the same problem. Is there any wrong with the configs?

**Comment by nikkiccq** [comment]
I have the same problem. Is there anything wrong with the configs?

**Comment by markgreenlqy** [comment]
@hli2020 Same problem. Can you help to solve this?

**Comment by haofengsiji** [comment]
It seems that something changed in congfig.py accidentally.
Try the old version.
`git a3e79f8`

**Comment by loadder** [comment]
> I guess that something was changed in 'congfig.py' accidentally.
> Try the old version.
> `git checkout a3e79f8`

Yes the branch you mentioned doesnt have this problem. Now i can start to reproduce the paper. Thanks!

**Comment by Jerr-boop** [comment]
hello,I want to konwn how to solve this problem,thank you!

**Comment by Jerr-boop** [comment]
> I just run as the readme writes
> `python main.py --yaml_file configs/demo/mini/20way_1shot.yaml`
> and i got this error
> `Traceback (most recent call last): File "main.py", line 204, in <module> main() File "main.py", line 28, in main opts = Config(config['options']['ctrl.yaml_file'], config['options']) File "/home/few-shot-ctm/core/config.py", line 111, in __init__ merge_cfg_from_file(yaml_file, self) File "/home/few-shot-ctm/tools/general_utils.py", line 278, in merge_cfg_from_file _merge_a_into_b(yaml_cfg, _config) File "/hom/few-shot-ctm/tools/general_utils.py", line 334, in _merge_a_into_b _merge_a_into_b(v, b[k], stack=stack_push) File "/home/few-shot-ctm/tools/general_utils.py", line 324, in _merge_a_into_b raise KeyError('Non-existent config key: {}'.format(full_key)) KeyError: 'Non-existent config key: ctmnet.pred_source'`
> python version 3.6.8 pytorch version 1.2.0
> Any idea?

can you tell me how to use the old vision? thank you !

**Comment by wsj1996** [comment]
sorry , I will reply u after a few days ok？&nbsp; I have some exams these days.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.Yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 上午7:03
收件人:&nbsp;"Clarifai/few-shot-ctm"<few-shot-ctm@noreply.github.com&gt;;
抄送:&nbsp;"陌离"<1924176640@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Clarifai/few-shot-ctm] Why i can't run the code with default setting (#8)





 
hello,I want to konwn how to solve this problem,thank you!

**Comment by ustcwangx** [comment]
I got the same problem, and there is no old version available here, could anyone tell me how to deal with this problem?

**Comment by Jerr-boop** [comment]
thank you all the way！




On 07/04/2020 16:40, wangx wrote:

I got the same problem, and there is no old version available here, could anyone tell me how to deal with this problem?

**Comment by ustcwangx** [comment]
> thank you all the way！ On 07/04/2020 16:40, wangx wrote: I got the same problem, and there is no old version available here, could anyone tell me how to deal with this problem? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reply!
But actually I didnot get what you mean...And I try `git checkout a3e79f8`，there are other terrible errors

**Comment by wangwdmagua** [comment]
> I just run as the readme writes
> `python main.py --yaml_file configs/demo/mini/20way_1shot.yaml`
> and i got this error
> `Traceback (most recent call last): File "main.py", line 204, in <module> main() File "main.py", line 28, in main opts = Config(config['options']['ctrl.yaml_file'], config['options']) File "/home/few-shot-ctm/core/config.py", line 111, in __init__ merge_cfg_from_file(yaml_file, self) File "/home/few-shot-ctm/tools/general_utils.py", line 278, in merge_cfg_from_file _merge_a_into_b(yaml_cfg, _config) File "/hom/few-shot-ctm/tools/general_utils.py", line 334, in _merge_a_into_b _merge_a_into_b(v, b[k], stack=stack_push) File "/home/few-shot-ctm/tools/general_utils.py", line 324, in _merge_a_into_b raise KeyError('Non-existent config key: {}'.format(full_key)) KeyError: 'Non-existent config key: ctmnet.pred_source'`
> python version 3.6.8 pytorch version 1.2.0
> Any idea?

I got the same problem, did you solve it? if you did , can you  tell me? Thank you very much!

**Comment by lcjjun1996** [comment]
Add "    ctmnet.pred_source = "" "  to line 40 of " ./core/comfig.py"
So are other issues

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/115361924-a1e20080-a1f3-11eb-8f6c-ddc1fd0514a8.png)

**Comment by WoshiBoluo** [comment]
Has anyone reproduced the results of the paper?
